{
  imports = [
    ./applications.nix
    ./apple-music.nix
    ./bitwarden.nix
    ./browser.nix
    ./hypr-island.nix
    ./file-manager.nix
    ./firefox.nix
    ./hyprland.nix
    ./hyprlock-media.nix
    ./icloud-keychain.nix
    ./input-method.nix
    ./kitty.nix
    ./legcord.nix
    ./pi
    ./steam-theme.nix
    ./stylix.nix
  ];
}
