{
  imports = [
    ./applications.nix
    ./apple-music.nix
    ./bitwarden.nix
    ./browser.nix
    ./codex.nix
    ./cua.nix
    ./hypr-island.nix
    ./file-manager.nix
    ./firefox.nix
    ./hyprland.nix
    ./hyperv-rendering.nix
    ./input-method.nix
    ./kitty.nix
    ./legcord.nix
    ./paseo-tailscale.nix
    ./steam-theme.nix
    ./stylix.nix
  ];
}
